import {
  Antenna,
  Atom,
  BatteryCharging,
  Beaker,
  BookMarked,
  BookOpen,
  BookOpenText,
  Bot,
  Box,
  Boxes,
  Brain,
  BrainCircuit,
  Briefcase,
  Building2,
  Calculator,
  ChartLine,
  CircuitBoard,
  ClipboardList,
  CodeXml,
  Cog,
  Compass,
  Construction,
  Cpu,
  Database,
  Dna,
  Droplets,
  Factory,
  Files,
  FlaskConical,
  FlaskRound,
  Flame,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  HardHat,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  ListChecks,
  type LucideIcon,
  type LucideProps,
  Magnet,
  MessageSquare,
  Microscope,
  Monitor,
  Network,
  NotebookText,
  Orbit,
  PencilRuler,
  Pi,
  Plug,
  Puzzle,
  Radio,
  RadioTower,
  Recycle,
  Rocket,
  Ruler,
  Satellite,
  Scale,
  ScrollText,
  Server,
  Shield,
  Sigma,
  Smartphone,
  Sprout,
  SquareFunction,
  Sun,
  Terminal,
  Thermometer,
  TrainFront,
  Waves,
  Wifi,
  Wind,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  laptop: Laptop,
  cpu: Cpu,
  zap: Zap,
  cog: Cog,
  "building-2": Building2,
  network: Network,
  sigma: Sigma,
  atom: Atom,
  "flask-conical": FlaskConical,
  "code-xml": CodeXml,
  box: Box,
  "book-open": BookOpen,
  leaf: Leaf,
  "circuit-board": CircuitBoard,
  database: Database,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  bot: Bot,
  calculator: Calculator,
  "square-function": SquareFunction,
  pi: Pi,
  "chart-line": ChartLine,
  globe: Globe,
  wifi: Wifi,
  radio: Radio,
  "radio-tower": RadioTower,
  antenna: Antenna,
  satellite: Satellite,
  waves: Waves,
  magnet: Magnet,
  orbit: Orbit,
  "battery-charging": BatteryCharging,
  plug: Plug,
  gauge: Gauge,
  thermometer: Thermometer,
  flame: Flame,
  wind: Wind,
  droplets: Droplets,
  sun: Sun,
  factory: Factory,
  wrench: Wrench,
  hammer: Hammer,
  "hard-hat": HardHat,
  construction: Construction,
  ruler: Ruler,
  "pencil-ruler": PencilRuler,
  compass: Compass,
  "train-front": TrainFront,
  rocket: Rocket,
  landmark: Landmark,
  terminal: Terminal,
  server: Server,
  monitor: Monitor,
  smartphone: Smartphone,
  layers: Layers,
  "git-branch": GitBranch,
  workflow: Workflow,
  boxes: Boxes,
  puzzle: Puzzle,
  shield: Shield,
  microscope: Microscope,
  dna: Dna,
  beaker: Beaker,
  sprout: Sprout,
  recycle: Recycle,
  lightbulb: Lightbulb,
  scale: Scale,
  briefcase: Briefcase,
  languages: Languages,
  "message-square": MessageSquare,
  "graduation-cap": GraduationCap,
  "book-open-text": BookOpenText,
  "notebook-text": NotebookText,
  "scroll-text": ScrollText,
  "flask-round": FlaskRound,
  "clipboard-list": ClipboardList,
  "list-checks": ListChecks,
  "book-marked": BookMarked,
  files: Files,
};

export const ICON_NAMES = Object.keys(ICONS);

export function DynamicIcon({ name, ...props }: { name: string | null | undefined } & LucideProps) {
  const Icon = (name && ICONS[name]) || BookOpen;
  return <Icon {...props} />;
}
